name: Test

on: [push, pull_request]

jobs:
  test_without_simd:
    name: ${{ matrix.os }}(no simd)
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-13, macos-14]

    steps:
    - uses: actions/checkout@v4

    - name: Build tests
      run: |
        cmake -S test -B build -Wno-dev
        cmake --build build

    - name: Run tests
      run: |
        cd build
        ctest -C Debug

  test_with_simd:
    name: ${{ matrix.os }}(simd)
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-13, macos-14]

    steps:
    - uses: actions/checkout@v4

    - name: Build simd tests
      run: |
        cmake -S test -B build -Wno-dev -DSINT_SIMD=ON
        cmake --build build

    - name: Run simd tests
      continue-on-error: true
      run: |
        cd build
        ctest -C Debug

    - name: test output
      if: matrix.os == 'windows-latest'
      run: |
        .\build\Debug\sint_test.exe

    - name: test output
      if: matrix.os != 'windows-latest'
      run: |
        ./build/sint_test
